import StyleDictionary from 'style-dictionary'
import { transformGroups } from 'style-dictionary/enums'

/** Strip color.{light|dark} so vars stay --background (not --color-background). */
function cssVarName(token) {
  const path = [...token.path]
  if (path[0] === 'color' && (path[1] === 'light' || path[1] === 'dark')) {
    path.splice(0, 2)
  }
  // shadow.DEFAULT → --shadow (not --shadow-default)
  if (path[0] === 'shadow' && path[1] === 'DEFAULT') {
    return 'shadow'
  }
  // type.display.size → type-display-size
  return path.join('-')
}

function tokenValue(token) {
  const v = token.$value ?? token.value
  if (typeof v === 'string') return v
  if (typeof v === 'number') return String(v)
  return String(v)
}

function decl(token) {
  return `  --${cssVarName(token)}: ${tokenValue(token)};`
}

StyleDictionary.registerFormat({
  name: 'css/ohmni-tokens',
  format: ({ dictionary }) => {
    const all = dictionary.allTokens

    const lightColors = all.filter(
      (t) => t.path[0] === 'color' && t.path[1] === 'light'
    )
    const darkColors = all.filter(
      (t) => t.path[0] === 'color' && t.path[1] === 'dark'
    )
    const shared = all.filter((t) => t.path[0] !== 'color')

    const root = [...lightColors, ...shared].map(decl).join('\n')
    const dark = darkColors.map(decl).join('\n')

    return `/**
 * Do not edit directly — generated by Style Dictionary from tokens/
 * Run: pnpm tokens:build
 */

:root {
${root}
}

.dark {
${dark}
}
`
  },
})

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: transformGroups.css,
      buildPath: 'app/(site)/generated/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/ohmni-tokens',
        },
      ],
    },
  },
}
